spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3356/cabinet_medical?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: INFO
    com.example: INFO
    web: DEBUG
  file:
    path: ./logs/logs.txt

